### ISSUE TITLE
Crash when scrolling on Parents fragement

### ISSUE THREAD

**Issue by trife** [PhenoApps/Intercross#7]
`2019-10-14 14:26:45.161 24280-24280/org.phenoapps.intercross E/MessageQueue-JNI: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter e1
        at org.phenoapps.intercross.fragments.ParentsFragment$gestureListener$1.onFling(Unknown Source:2)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:656)
        at androidx.core.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:480)
        at androidx.core.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:543)
        at org.phenoapps.intercross.fragments.ParentsFragment$afterCreateView$5.onTouch(ParentsFragment.kt:172)
        at android.view.View.dispatchTouchEvent(View.java:12509)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
        at android.view.View.dispatchPointerEvent(View.java:12752)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5107)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4910)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4480)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4446)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4586)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4454)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4643)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4480)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4446)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4454)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7093)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7062)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7023)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7196)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
2019-10-14 14:26:45.162 24280-24280/org.phenoapps.intercross D/AndroidRuntime: Shutting down VM`

`2019-10-14 14:26:45.167 24280-24280/org.phenoapps.intercross E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.phenoapps.intercross, PID: 24280
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter e1
        at org.phenoapps.intercross.fragments.ParentsFragment$gestureListener$1.onFling(Unknown Source:2)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:656)
        at androidx.core.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:480)
        at androidx.core.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:543)
        at org.phenoapps.intercross.fragments.ParentsFragment$afterCreateView$5.onTouch(ParentsFragment.kt:172)
        at android.view.View.dispatchTouchEvent(View.java:12509)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
        at android.view.View.dispatchPointerEvent(View.java:12752)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5107)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4910)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4480)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4446)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4586)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4454)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4643)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4480)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4446)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4454)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7093)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7062)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7023)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7196)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
2019-10-14 14:26:45.167 24280-24280/org.phenoapps.intercross E/AndroidRuntime:     at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by chaneylc** [comment]
https://github.com/PhenoApps/Intercross/commit/f4b47d3bc0b9b1853a78c4ca9ce23a5d44415e3d

Recycler view is now scrollable.
